image: soxueren/docker-maven:latest

variables:
  REGISTRY_URL: "soxueren"
  IMAGE_TAG: "8.5-jre8-alpine"

services:
  - docker:dind

stages:
  - build

before_script:
  - docker info

build-master:
  stage: build
  script:
    - docker build --pull -t $REGISTRY_URL/tomcat:$IMAGE_TAG .
    - docker push $REGISTRY_URL/tomcat:$IMAGE_TAG

